### PR TITLE
Use a map for routes instead of iterating

### PR DESCRIPTION
**Pull request by bd452**
In the original implementation, routes were iterated through one-by-one at runtime. This could cause a performance slowdown as new routes are added.

This PR generates a Map of all possible routes at startup, and then references that map when routing.

### CODE REVIEW

**Comment by jablonski** [comment]
Hi Bryce,

thanks for the PR, I like the idea of caching routes, but I see two problems:

- In development mode new routes are not picked up automagically, so the server instance has to be restarted on each addition of a new route handler (and therefore for any change in serverside code). This might be very anoying if you use caches, sessions, database pools etc.pp. which might take some time to get filled and you don't want to constantly loosing them.

- As Jeasx supports serverless hosting (e.g. Vercel) and server-based hosting (e.g. classical Node hosting), a problem arises with serverless hosting: the initial serverless function needs more time to get started because all routes are calculated before anything is served.

Idea could be to use the existing implementation and build up a route cache at runtime (only for production). This would help the serverless scenario not much (only if your function is reused several times before it gets killed), but this wouldn't make the startup not slower. And for server-based hosting this would improve performance as your implementation.

Important question after all: Usually the route checks at runtime are very fast for me (about a millisecond for my projects). Maybe you can elaborate the scenario where this might take too much time? Just to prevent some kind of premature optimization, which is the root of all evil...;-)

Cheers, Maik

**Comment by jablonski** [comment]
Hi Bryce,

I've implemented the "runtime cache" in my sandbox project:

https://github.com/jablonski/jeasx-sandbox/blob/main/serverless.ts 

The results are good. For a single request it comes down to 1-2 milliseconds (hard to measure), but running huge loads of requests via a benchmark tool results in a performance improvement by factor 2.

Maybe you can have a look before I merge this into the main project?

**Comment by jablonski** [comment]
I've integrated the runtime cache in Jeasx core, so I'm closing the PR.

https://github.com/jeasx/jeasx/blob/main/serverless.ts

**Comment by jablonski** [comment]
Changes are released today with Jeasx 1.2.0. Thanks for bringing this topic onto the radar!

**Comment by bd452** [comment]
Glad to be of service!

**Pull request closed without merging**
